version: '2'

services:
  app:
    image: 'ezra_lending_api:latest'
    build:
      context: .
    container_name: ezra_lending_api
    depends_on:
      - ezra_lending_db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ezra_lending_db:5432/ezra_elevator
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - '8090:8090'


  ezra_lending_db:
    image: 'postgres:13.1-alpine'
    container_name: ezra_lending_db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=ezra_lending
    ports:
      - '5438:5432'

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
